#!/usr/bin/env python

import argparse
import configparser
import cv2
import os
import numpy

if(__name__ == "__main__"):

    cap = cv2.VideoCapture(0)
    qrCodeDetector = cv2.QRCodeDetector()
    
    cv2.namedWindow('frame' , cv2.WINDOW_NORMAL)

    try:
    
        while(True):
            
            # Capture frame-by-frame
            ret, frame = cap.read()
           
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            aruco_dict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_4X4_250)
            parameters =  cv2.aruco.DetectorParameters_create()
            corners, ids, rejectedImgPoints = cv2.aruco.detectMarkers(gray, aruco_dict, parameters=parameters)
            frame_markers = cv2.aruco.drawDetectedMarkers(frame.copy(), corners, ids)
            
            # find QR code
            #decoded = qrCodeDetector.detectAndDecode(frame)

            #print("---" , corners , "---")

            cv2.imshow('frame',frame_markers)

            key = cv2.waitKey(1)
 
            if(key == ord('q')):
                break

    finally:

        cap.release()
        cv2.destroyAllWindows()

